// src/features/products/productServices.js
const productServices = [
  {
    id: 1,
    name: "Hydrating Facial Cleanser",
    category: "Skin Care",
    price: 50,
    rating: 4.5,
    available: true,
    image: "https://images.pexels.com/photos/8155444/pexels-photo-8155444.jpeg",
  },
  {
    id: 2,
    name: "Anti-Aging Serum",
    category: "Skin Care",
    price: 80,
    rating: 4.8,
    available: true,
    image: "https://images.pexels.com/photos/4841353/pexels-photo-4841353.jpeg",
  },
  {
    id: 3,
    name: "Vitamin C Moisturizer",
    category: "Skin Care",
    price: 50,
    rating: 4.2,
    available: false,
    image: "https://images.pexels.com/photos/14788548/pexels-photo-14788548.jpeg",
  },
  {
    id: 4,
    name: "Herbal Hair Shampoo",
    category: "Hair Care",
    price: 90,
    rating: 4.3,
    available: true,
    image: "https://images.pexels.com/photos/13573922/pexels-photo-13573922.jpeg",
  },
  {
    id: 5,
    name: "Argan Oil Conditioner",
    category: "Hair Care",
    price: 110,
    rating: 4.4,
    available: true,
    image: "https://images.pexels.com/photos/8467975/pexels-photo-8467975.jpeg",
  },
  {
    id: 6,
    name: "Matte Liquid Foundation",
    category: "Makeup",
    price: 180,
    rating: 4.7,
    available: true,
    image: "https://images.pexels.com/photos/20903469/pexels-photo-20903469.jpeg",
  },
  {
    id: 7,
    name: "Velvet Lipstick Set",
    category: "Makeup",
    price: 130,
    rating: 4.6,
    available: false,
    image: "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg",
  },
  {
    id: 8,
    name: "Aloe Vera Body Lotion",
    category: "Body Care",
    price: 100,
    rating: 4.1,
    available: true,
    image: "https://images.pexels.com/photos/4465830/pexels-photo-4465830.jpeg",
  },
  {
    id: 9,
    name: "Shea Butter Cream",
    category: "Body Care",
    price: 95,
    rating: 4.3,
    available: true,
    image: "https://images.pexels.com/photos/17596984/pexels-photo-17596984.jpeg",
  },

  {
    id: 10,
    name: "Rose Mist Toner",
    category: "Skin Care",
    price: 140,
    rating: 4.5,
    available: true,
    image: "https://images.pexels.com/photos/16181774/pexels-photo-16181774.jpeg",
  },
  {
    id: 11,
    name: "Charcoal Face Mask",
    category: "Skin Care",
    price: 160,
    rating: 4.4,
    available: true,
    image: "https://images.pexels.com/photos/4004470/pexels-photo-4004470.jpeg",
  },
  {
    id: 12,
    name: "Coconut Hair Serum",
    category: "Hair Care",
    price: 115,
    rating: 4.5,
    available: true,
    image: "https://images.pexels.com/photos/3762882/pexels-photo-3762882.jpeg",
  },
  {
    id: 13,
    name: "Organic Body Scrub",
    category: "Body Care",
    price: 125,
    rating: 4.2,
    available: false,
    image: "https://images.pexels.com/photos/5113056/pexels-photo-5113056.jpeg",
  },
  {
    id: 14,
    name: "Nude Eyeshadow Palette",
    category: "Makeup",
    price: 210,
    rating: 4.9,
    available: true,
    image: "https://images.pexels.com/photos/6662825/pexels-photo-6662825.jpeg",
  },
  {
    id: 15,
    name: "Hair Growth Oil",
    category: "Hair Care",
    price: 150,
    rating: 4.6,
    available: true,
    image: "https://images.pexels.com/photos/7608337/pexels-photo-7608337.jpeg",
  },
  {
    id: 16,
    name: "Collagen Day Cream",
    category: "Skin Care",
    price: 170,
    rating: 4.8,
    available: true,
    image: "https://images.pexels.com/photos/4735944/pexels-photo-4735944.jpeg",
  },
  {
    id: 17,
    name: "Lavender Body Wash",
    category: "Body Care",
    price: 105,
    rating: 4.5,
    available: true,
    image: "https://images.pexels.com/photos/6690895/pexels-photo-6690895.jpeg",
  },
  {
    id: 18,
    name: "Hydra Boost Gel",
    category: "Skin Care",
    price: 155,
    rating: 4.6,
    available: true,
    image: "https://images.pexels.com/photos/6496458/pexels-photo-6496458.jpeg",
  },
  {
    id: 19,
    name: "Caffeine Eye Mask",
    category: "Skin Care",
    price: 135,
    rating: 4.3,
    available: true,
    image: "https://images.pexels.com/photos/6706884/pexels-photo-6706884.jpeg",
  },
  {
    id: 20,
    name: "Keratin Hair Mask",
    category: "Hair Care",
    price: 130,
    rating: 4.4,
    available: true,
    image: "https://images.pexels.com/photos/32435039/pexels-photo-32435039.jpeg",
  },
];

export default productServices;
